# Generated by Django 3.2.18 on 2023-03-23 17:48

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0013_auto_20211103_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuree',
            options={'managed': True},
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='education',
            field=models.ForeignKey(blank=True, db_column='Education', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.education'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='family',
            field=models.ForeignKey(blank=True, db_column='FamilyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='insuree.family'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.gender'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='health_facility',
            field=models.ForeignKey(blank=True, db_column='HFID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='JsonExt', null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='photo',
            field=models.OneToOneField(blank=True, db_column='PhotoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='insuree.insureephoto'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='profession',
            field=models.ForeignKey(blank=True, db_column='Profession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.profession'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='relationship',
            field=models.ForeignKey(blank=True, db_column='Relationship', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.relation'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='type_of_id',
            field=models.ForeignKey(blank=True, db_column='TypeOfId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.identificationtype'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='uuid',
            field=models.CharField(db_column='InsureeUUID', default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='current_village',
            field=models.ForeignKey(blank=True, db_column='CurrentVillage', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='row_id',
            field=models.BigIntegerField(blank=True, db_column='RowID', null=True),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='validity_from',
            field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        ),
    ]

