# Generated by Django 3.2.18 on 2023-03-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0015_auto_20230323_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuree',
            options={'managed': True},
        ),
    ]
