# Generated by Django 3.2.18 on 2023-03-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0017_auto_20230323_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(db_column='AccessTokenID', primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('expiry_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
