# Generated by Django 3.2.18 on 2023-03-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0018_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
