# Generated by Django 3.2.18 on 2023-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0019_accesstoken_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
