# Generated by Django 3.2.18 on 2023-03-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0020_alter_accesstoken_expiry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeraUtilities',
            fields=[
                ('id', models.AutoField(db_column='HeraUtilitiesID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField()),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('subscription_uuid', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
