# Generated by Django 3.2.18 on 2023-03-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0022_auto_20230325_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='audit_user_id',
            field=models.BigIntegerField(db_column='AuditUserID'),
        ),
    ]
